# Generated by Django 3.2.2 on 2021-06-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
        ('category', '0003_alter_category_cat_image'),
    ]

    operations = [
    ]
