# Generated by Django 3.2.2 on 2021-06-26 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_variations_variation'),
        ('orders', '0004_alter_orderitem_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.payment'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
